[SCRIPT]
Version=0.3.8.5
Date=16.11.2022
Url=https://github.com/PSI4T/prahk/blob/master/apps/PRASMART.exe?raw=true
Name=PRASMART
Delete=
[URL]
Accounts=https://raw.githubusercontent.com/PSI4T/prahk/master/family/accounts/register/
Twinks=https://raw.githubusercontent.com/PSI4T/prahk/master/family/accounts/twinks/
Rank=https://raw.githubusercontent.com/PSI4T/prahk/master/family/ranks/rank
Info=https://raw.githubusercontent.com/PSI4T/prahk/master/family/baseinfo.p4
Config=https://raw.githubusercontent.com/PSI4T/prahk/master/apps/settings/screensize/
BlackList=https://raw.githubusercontent.com/PSI4T/prahk/master/family/blacklist.p4
