[Family]
Bank=17900000
Engraving=PRA
ExpNormal=4
RepNorm=2
CashNorm=8000
ListName=Vasiliy_Petrushka|Conor_Hokage|Daniil_Petrushka|Danil_Everestov|Iluxa_Zaxarov|Nekit_Grebnev|Nikita_Everestov|Sergey_Grebnev|Tim_Tsibin|Stanislav_Kingsman|Jordan_Coffeino|Kendrick_Petrushka|Vlad_Forester|Alina_Zakon
Color=2